# Use a base image with Python
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /image_rest_api

# Copy the requirements file and install dependencies
COPY ../requirements.txt .
RUN pip install -r requirements.txt

# Copy the application code
COPY ./image_rest_api/ .
COPY ./shared ./shared

# Expose the port Flask will run on
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "main:app"]