# Use a base image with Python
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /web_server

# Copy the requirements file and install dependencies
COPY ../requirements.txt .
RUN pip install -r requirements.txt

# Copy the application code
COPY ./web_server/ .
COPY ./shared ./shared

# Expose the port Flask will run on
EXPOSE 5000

# Command to run the application
CMD ["python", "main.py"]